version: '3'

services:

  elasticsearch:
    build:
      context: ./docker-elk/elasticsearch/
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - ./volumes/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      mirror:
        ipv4_address: 172.20.0.50

  logstash:
    build:
      context: ./docker-elk/logstash/
    container_name: logstash
    hostname: logstash
    volumes:
      - ./volumes/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./volumes/logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      mirror:
        ipv4_address: 172.20.0.51
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./docker-elk/kibana/
    container_name: kibana
    hostname: kibana
    volumes:
      - ./volumes/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "8060:5601"
    networks:
      mirror:
        ipv4_address: 172.20.0.52
    depends_on:
      - elasticsearch

  apache:
    build: ./components/apache/
    restart: always
    networks:
      external:

  flask:
    build: ./components/flask/
    restart: always
    networks:
      external:

  client:
    build: ./components/client/
    container_name: client
    hostname: client
    dns:
      - "172.18.0.100"
    cap_add:
      - NET_ADMIN
    networks:
      internal:
        ipv4_address: 172.18.0.15

  bro:
    build: ./components/bro/
    container_name: bro
    hostname: bro
    volumes:
      - ./components/bro/config/opt/bro/share/bro/site/local.bro:/opt/bro/share/bro/site/local.bro:ro
      - ./components/bro/config/etc/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
    cap_add:
      - NET_ADMIN
    networks:
      mirror:
        ipv4_address: 172.20.0.15

  router:
    build: ./components/router/
    container_name: router
    hostname: router
    cap_add:
      - NET_ADMIN
    networks:
      mirror:
        ipv4_address: 172.20.0.100
      internal:
        ipv4_address: 172.18.0.100
      external:
        ipv4_address: 172.19.0.100

  misp-web:
    build: misp-docker/misp-web
    container_name: misp-web
    hostname: misp-web
    depends_on:
      - misp-db
    image: misp-web:latest
    restart: always
    networks:
      mirror:
        ipv4_address: 172.20.0.20
    links:
      - misp-db
    ports:
      - 8040:80
    volumes:
      - ./volumes/misp-web:/var/www/MISP
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_MISP_PASSWORD=misp
      - MYSQL_HOST=misp-db
      - MISP_ADMIN_EMAIL=admin@admin.test
      - MISP_ADMIN_PASSPHRASE=misp
      - MISP_BASEURL=http:\/\/misp\.test
      - POSTFIX_RELAY_HOST=relay.fqdn
      - TIMEZONE=Europe/London

  misp-db:
    build:
      context: misp-docker/misp-db
      args:
        MYSQL_MISP_PASSWORD: misp
    container_name: misp-db
    hostname: misp-db
    image: misp-db:latest
    restart: always
    networks:
      mirror:
        ipv4_address: 172.20.0.21
    volumes:
      - ./volumes/misp-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

networks:
  mirror:
    external:
      name: mirror
  internal:
    external:
      name: internal
  external:
    external:
      name: external
