version: '3'

services:

  elasticsearch:
    build:
      context: ./repos/docker-elk/elasticsearch/
      args:
        ELK_VERSION: '6.4.3'
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - ./volumes/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      mirror:
        ipv4_address: 172.20.0.50

  logstash-bro:
    build:
      context: ./repos/docker-elk/logstash/
      args:
        ELK_VERSION: '6.4.3'
    container_name: logstash-bro
    hostname: logstash-bro
    volumes:
      - ./volumes/logstash-bro/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./volumes/logstash-bro/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      mirror:
        ipv4_address: 172.20.0.51
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./repos/docker-elk/kibana/
      args:
        ELK_VERSION: '6.4.3'
    container_name: kibana
    hostname: kibana
    volumes:
      - ./volumes/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "8060:5601"
    networks:
      mirror:
        ipv4_address: 172.20.0.52
    depends_on:
      - elasticsearch

  logstash-flow:
    build:
      context: ./repos/docker-elk/logstash-flow/
      args:
        ELK_VERSION: '6.4.3'
    container_name: logstash-flow
    hostname: logstash-flow
    volumes:
      - ./volumes/logstash-flow/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./volumes/logstash-flow/pipeline:/usr/share/logstash/pipeline:ro
      - ./volumes/logstash-flow/elastiflow:/usr/share/logstash/elastiflow:ro
      - ./volumes/logstash-flow/profile.d/elastiflow.sh:/etc/profile.d/elastiflow.sh:ro
      - ./volumes/logstash-flow/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      mirror:
        ipv4_address: 172.20.0.53
    depends_on:
      - elasticsearch

  #elastalert:
  #  build: ./components/elastalert/
  #  container_name: elastalert
  #  hostname: elastalert
  #  volumes:
  #    - ./components/elastalert/config/:/config
  #  restart: always
  #  networks:
  #    mirror:
  #  depends_on:
  #    - elasticsearch

  apache:
    build: ./components/apache/
    restart: always
    networks:
      external:

  flask:
    build: ./components/flask/
    restart: always
    networks:
      external:

  ssh:
    build: ./components/ssh/
    restart: always
    networks:
      external:

  client:
    build: ./components/client/
    container_name: client
    hostname: client
    volumes:
      - ./components/client/files/:/files
    dns:
      - "172.18.0.100"
    cap_add:
      - NET_ADMIN  
    networks:
      internal:
        ipv4_address: 172.18.0.15

  bro:
    build: ./components/bro/
    container_name: bro
    hostname: bro
    volumes:
      - ./components/bro/config/opt/bro/share/bro/site/local.bro:/opt/bro/share/bro/site/local.bro:ro
      - ./components/bro/config/etc/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
    cap_add:
      - NET_ADMIN
    networks:
      mirror:
        ipv4_address: 172.20.0.15

  router:
    build: ./components/router/
    container_name: router
    hostname: router
    volumes:
      - ./components/router/files/:/files
    cap_add:
      - NET_ADMIN
    networks:
      mirror:
        ipv4_address: 172.20.0.100
      internal:
        ipv4_address: 172.18.0.100
      external:
        ipv4_address: 172.19.0.100
    depends_on:
      - kibana

  misp-web:
    build: repos/misp-docker/misp-web
    container_name: misp-web
    hostname: misp-web
    depends_on:
      - misp-db
    image: misp-web:latest
    restart: always
    networks:
      mirror:
        ipv4_address: 172.20.0.20
    links:
      - misp-db
    ports:
      - 8040:80
    volumes:
      - ./volumes/misp-web:/var/www/MISP
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_MISP_PASSWORD=misp
      - MYSQL_HOST=misp-db
      - MISP_ADMIN_EMAIL=admin@admin.test
      - MISP_ADMIN_PASSPHRASE=misp
      - MISP_BASEURL=http:\/\/misp\.test
      - POSTFIX_RELAY_HOST=relay.fqdn
      - TIMEZONE=Europe/London

  misp-db:
    build:
      context: repos/misp-docker/misp-db
      args:
        MYSQL_MISP_PASSWORD: misp
    container_name: misp-db
    hostname: misp-db
    image: misp-db:latest
    restart: always
    networks:
      mirror:
        ipv4_address: 172.20.0.21
    volumes:
      - ./volumes/misp-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

networks:
  mirror:
    external:
      name: mirror
  internal:
    external:
      name: internal
  external:
    external:
      name: external
