#! /bin/bash

if [ -z $SOCDIR ]; then
    SOCDIR=`pwd`
fi

read -p "Telegram bot token: " token 
read -p "Telegram room id: " room_id

echo $token
echo $room_id

docker exec elastalert bash -c "sed -i \"s/REPLACE_WITH_BOT_TOKEN/$token/;s/REPLACE_WITH_BOT_ROOM_ID/$room_id/\" /config/rules/*.yaml"

cd $SOCDIR

docker-compose restart elastalert
