#! /bin/bash

if [ -z $SOCDIR ]; then
    SOCDIR=`pwd`
fi

if [ -z $MISP_HOST ]; then
    export MISP_HOST="localhost"
fi

if [ "$#" -ne 1 ]; then
    scale=1
else
    scale=$1
fi

logfile=$SOCDIR"/log/run-"`date +%s`".log"

$SOCDIR/pocketsoc_configure $SOCDIR

echo "Starting up, see $logfile"

cd $SOCDIR

$SOCDIR/pocketsoc_misp_setup &

/usr/local/bin/docker-compose up --remove-orphans > $logfile 2>&1 &
