#! /bin/bash

if [ -z $SOCDIR ]; then
    SOCDIR=`pwd`
fi

if [ -z $MISP_HOST ]; then
    export MISP_HOST="localhost"
fi

cd $SOCDIR

docker-compose stop
git checkout $SOCDIR/components/elastalert/config/rules/misp_src.yaml
git checkout $SOCDIR/components/elastalert/config/rules/zeek-intel.yaml
