#! /bin/bash

SECONDS=0

if [ -z $SOCDIR ]; then
    SOCDIR=`pwd`
fi

if [ -z $MISP_HOST ]; then 
    export MISP_HOST="localhost"
fi

echo "Using $MISP_HOST as hostname" | tee $logfile

logfile=$SOCDIR"/log/build-"`date +%s`".log"

$SOCDIR/pocketsoc_configure $SOCDIR

echo "Starting up, see $logfile"

cd $SOCDIR

/usr/local/bin/docker-compose config | tee -a $logfile

/usr/local/bin/docker-compose build --parallel --force-rm --compress --pull 2>&1  | tee -a $logfile


wait
timelapse=`echo "scale=1;$SECONDS/60" | bc`
echo `date`" $timelapse minutes elapsed" | tee -a $logfile
echo "Build complete"
