#! /bin/bash

/opt/bro/bin/broctl deploy
/files/watchmisp.sh &
/usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat &
tail -f /dev/null
