filebeat.inputs:

- input_type: log
  paths: 
    - "/opt/bro/logs/current/capture_loss.log"
  fields:
    type: "zeek-capture_loss"
  fields_under_root: true
 
- input_type: log
  paths: 
    - "/opt/bro/logs/current/conn.log"
  fields:
    type: "zeek-conn"
  fields_under_root: true
 
- input_type: log
  paths: 
    - "/opt/bro/logs/current/dpd.log"
  fields:
    type: "zeek-dpd"
  fields_under_root: true
 
- input_type: log
  paths: 
    - "/opt/bro/logs/current/dhcp.log"
  fields:
    type: "zeek-dhcp"
  fields_under_root: true
 
- input_type: log
  paths: 
    - "/opt/bro/logs/current/dns.log"
  fields:
    type: "zeek-dns"
  fields_under_root: true
 
- input_type: log
  paths: 
    - "/opt/bro/logs/current/intel.log"
  fields:
    type: "zeek-intel"
  fields_under_root: true
 
- input_type: log
  paths:
    - "/opt/bro/logs/current/files.log"
  fields:
    type: "zeek-files"
  fields_under_root: true

- input_type: log
  paths:
    - "/opt/bro/logs/current/http.log"
  fields:
    type: "zeek-http"
  fields_under_root: true

- input_type: log
  paths:
    - "/opt/bro/logs/current/ssl.log"
  fields:
    type: "zeek-ssl"
  fields_under_root: true

- input_type: log
  paths: 
    - "/opt/bro/logs/current/stats.log"
  fields:
    type: "zeek-stats"
  fields_under_root: true
 
- input_type: log
  paths: 
    - "/opt/bro/logs/current/weird.log"
  fields:
    type: "zeek-weird"
  fields_under_root: true
 
- input_type: log
  paths: 
    - "/opt/bro/logs/current/x509.log"
  fields:
    type: "zeek-x509"
  fields_under_root: true
 
output.logstash:
  # The Logstash hosts
  hosts: ["172.20.0.51:5044"]
