es_host: elasticsearch
es_port: 9200
name: match zeek-intel
index: zeek-*

realert:
  minutes: 10

exponential_realert:
  hours: 1

type: any

filter:
- query:
    query_string:
      query: "type: \"zeek-intel\""

# Insert alert details here

alert:
- "telegram"

alert_text_type: aggregation_summary_only

telegram_bot_token: REPLACE_WITH_BOT_TOKEN
telegram_room_id: "REPLACE_WITH_BOT_ROOM_ID"
