#! /bin/bash

# Confirm client,webserver interfaces

external_subnet="172.19"
internal_subnet="172.18"

# Define interfaces

external=`ifconfig | grep -B 1 $external_subnet | grep ^eth | awk '{print $1}' | cut -d: -f1`
internal=`ifconfig | grep -B 1 $internal_subnet | grep ^eth | awk '{print $1}' | cut -d: -f1`

# Configure routing

iptables -t nat -A POSTROUTING -o $external -j MASQUERADE
iptables -A FORWARD -i $external -o $internal -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $internal -o $external -j ACCEPT

## Configure NFLOG
#
#iptables -t mangle -A PREROUTING -j NFLOG --nflog-group 10
#iptables -t mangle -A PREROUTING -j NFLOG --nflog-group 10
#iptables -t mangle -A POSTROUTING -j NFLOG --nflog-group 10

# Configure mirroring

iptables -t mangle -A PREROUTING -j TEE -i eth0 --gateway bro.mirror
iptables -t mangle -A PREROUTING -j TEE -i eth2 --gateway bro.mirror
iptables -t mangle -A POSTROUTING -j TEE --gateway bro.mirror
