#! /bin/bash

sleeptime=5

echo "Applying routing rules"

/files/routing

(
echo "Starting up DNS proxy"
/usr/sbin/dnsmasq -k &
)

#echo "Running hsflowd"
#while [ `iptables -L -n -t mangle | grep nflog | wc -l` -eq 0 ]; do
#    echo "Waiting for firewall rules"
#    sleep 10
#done
#echo "Firewall rules in place"
#
#machineid=`uuidgen`
#/usr/sbin/hsflowd -u $machineid -f /files/hsflowd.conf &

sleeptime=150

while ! nc -z -w 1 172.20.0.50 9200; do
    echo "Not connected to elasticsearch, sleeping for $sleeptime seconds..."
    sleep $sleeptime
done

while ! nc -z -w 1 172.20.0.52 5601; do
    echo "Not connected to kibana, sleeping for $sleeptime seconds..."
    sleep $sleeptime
done

/files/import_patterns.sh

echo Startup complete


tail -f /dev/null
